name: "nightly-release"

on:
  push:
    branches: [ master ]

env:
    CONFIG_ARTIFACT: release-config
    CONFIG_ARTIFACT_PATH: release-config.txt
    SDL2_ARTIFACT: release-sdl2
    SDL2_ARTIFACT_PATH: release-sdl2.txt
    SDL2_ARCHIVE_ARTIFACT: release-sdl2-archive
    SDL12_ARTIFACT: release-sdl12
    SDL12_ARTIFACT_PATH: release-sdl12.txt
    SDL12_ARCHIVE_ARTIFACT: release-sdl12-archive

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      # Need commit history
      - name: Clone Project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Vars
        id: get_vars
        run: |
          version=`git rev-parse --verify --short HEAD`
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Artifact with Configuration Details
        run: |
          echo version= '${{ steps.get_vars.outputs.version }}' >> $CONFIG_ARTIFACT_PATH

      - name: Upload Artifact for Use by Dependent Steps
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONFIG_ARTIFACT }}
          path: ${{ env.CONFIG_ARTIFACT_PATH }}
          retention-days: 1

  linux_sdl2_x86_64:
    needs: setup
    name: Build (Linux)(SDL2)(x86_64)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Download Artifact with Configuration Information
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CONFIG_ARTIFACT }}

      - name: Extract Configuration Information and Store in Step Outputs
        id: store_config
        run: |
          version=`sed -E -n -e 's/version= //p' $CONFIG_ARTIFACT_PATH`
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl2-dev libsdl2-image-dev

      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: create_linux_sdl2_x86_64_archive
        run: |
          make -j$(nproc) sdl2 SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="FinalBurn Neo (Linux)(SDL2)(x86_64).zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths ${archive_file} fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}' > $SDL2_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SDL2_ARTIFACT }}
          path: ${{ env.SDL2_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SDL2_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  linux_sdl12_x86_64:
    needs: setup
    name: Build (Linux)(SDL1.2)(x86_64)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Download Artifact with Configuration Information
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CONFIG_ARTIFACT }}

      - name: Extract Configuration Information and Store in Step Outputs
        id: store_config
        run: |
          version=`sed -E -n -e 's/version= //p' $CONFIG_ARTIFACT_PATH`
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl1.2-dev

      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: create_linux_sdl12_x86_64_archive
        run: |
          make -j$(nproc) sdl SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="FinalBurn Neo (Linux)(SDL1.2)(x86_64).zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths ${archive_file} fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl12_x86_64_archive.outputs.archive_file }}' > $SDL12_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SDL12_ARTIFACT }}
          path: ${{ env.SDL12_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SDL12_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl12_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  release:
    needs: [ setup, source, linux_sdl2_x86_64, linux_sdl12_x86_64 ]
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact with Configuration Information
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.CONFIG_ARTIFACT }}

      - name: Extract Configuration Information and Store in Step Outputs
        id: store_config
        run: |
          version=`sed -E -n -e 's/version= //p' $CONFIG_ARTIFACT_PATH`
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Download Artifact (Linux)(SDL2)(x86_64) 
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SDL2_ARTIFACT }}

      - name: Extract Archive Path (Linux)(SDL2)(x86_64) and Store in Step Outputs
        id: store_linux_sdl2_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $SDL2_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux)(SDL2)(x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SDL2_ARCHIVE_ARTIFACT }}

      - name: Download Artifact (Linux)(SDL1.2)(x86_64) 
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SDL12_ARTIFACT }}

      - name: Extract Archive Path (Linux)(SDL1.2)(x86_64) and Store in Step Outputs
        id: store_linux_sdl12_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $SDL12_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux)(SDL1.2)(x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SDL12_ARCHIVE_ARTIFACT }}

      - name: Populate Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.store_config.outputs.version }}
          name: ${{ steps.store_config.outputs.version }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: true
          make_latest: true
          files: |
            ${{ steps.store_linux_sdl2_x86_64.outputs.archive_path }}
            ${{ steps.store_linux_sdl12_x86_64.outputs.archive_path }}
          token: ${{ secrets.GITHUB_TOKEN }}
