name: "nightly-release"

on:
  push:
    branches: [ master ]

env:
    LINUX_SDL2_X86_64_ARTIFACT: linux-sdl2-x86_64
    LINUX_SDL2_X86_64_ARTIFACT_PATH: linux-sdl2-x86_64.txt
    LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT: linux-sdl2-x86_64-archive
    LINUX_SDL1_X86_64_ARTIFACT: linux-sdl1-x86_64
    LINUX_SDL1_X86_64_ARTIFACT_PATH: linux-sdl1-x86_64.txt
    LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT: linux-sdl1-x86_64-archive
    WINDOWS_X86_64_ARTIFACT: windows-x86_64
    WINDOWS_X86_64_ARTIFACT_PATH: windows-x86_64.txt
    WINDOWS_X86_64_ARCHIVE_ARTIFACT: windows-x86_64-archive

jobs:
  build_windows_x86_64:
    name: Build (Windows x86_64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: msys2-devel base-devel binutils mingw-w64-x86_64-toolchain mingw-w64-x86_64-nasm zip wget
          msystem: MINGW64

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_windows_x86_64_archive
        run: |
          make -j$(nproc) mingw BUILD_X64_EXE=1 SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.WINDOWS_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo64.exe src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_windows_x86_64_archive.outputs.archive_file }}' > $WINDOWS_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARTIFACT }}
          path: ${{ env.WINDOWS_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_windows_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  build_linux_sdl2_x86_64:
    name: Build (Linux SDL2 x86_64)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl2-dev libsdl2-image-dev

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_linux_sdl2_x86_64_archive
        run: |
          make -j$(nproc) sdl2 SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.LINUX_SDL2_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}' > $LINUX_SDL2_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARTIFACT }}
          path: ${{ env.LINUX_SDL2_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl2_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  build_linux_sdl1_x86_64:
    name: Build (Linux SDL1 x86_64)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libsdl1.2-dev

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        id: create_linux_sdl1_x86_64_archive
        run: |
          make -j$(nproc) sdl SKIPDEPEND=1 RELEASEBUILD=1
          archive_file="${{ env.LINUX_SDL1_X86_64_ARTIFACT }}.zip"
          echo "archive_file=${archive_file}" >> $GITHUB_OUTPUT
          zip --junk-paths "${archive_file}" fbneo src/license.txt fbahelpfilesrc/fbneo.chm whatsnew.html

      - name: Create Archive Path
        run: |
          echo archive_path= '${{ steps.create_linux_sdl1_x86_64_archive.outputs.archive_file }}' > $LINUX_SDL1_X86_64_ARTIFACT_PATH

      - name: Upload Archive Path
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARTIFACT }}
          path: ${{ env.LINUX_SDL1_X86_64_ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT }}
          path: ${{ steps.create_linux_sdl1_x86_64_archive.outputs.archive_file }}
          retention-days: 1

  release:
    needs: [ build_windows_x86_64, build_linux_sdl2_x86_64, build_linux_sdl1_x86_64 ]
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Windows x86_64
      - name: Download Artifact (Windows x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Windows x86_64) and Store in Step Outputs
        id: store_windows_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $WINDOWS_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Windows x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.WINDOWS_X86_64_ARCHIVE_ARTIFACT }}

      # Linux SDL2 x86_64
      - name: Download Artifact (Linux SDL2 x86_64) 
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Linux SDL2 x86_64) and Store in Step Outputs
        id: store_linux_sdl2_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $LINUX_SDL2_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux SDL2 x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL2_X86_64_ARCHIVE_ARTIFACT }}

      # Linux SDL1 x86_64
      - name: Download Artifact (Linux SDL1 x86_64) 
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARTIFACT }}

      - name: Extract Archive Path (Linux SDL1 x86_64) and Store in Step Outputs
        id: store_linux_sdl1_x86_64
        run: |
          archive_path=`sed -E -n -e 's/archive_path= //p' $LINUX_SDL1_X86_64_ARTIFACT_PATH`
          echo "archive_path=$archive_path" >> $GITHUB_OUTPUT

      - name: Download Artifact with Archive (Linux SDL1 x86_64)
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LINUX_SDL1_X86_64_ARCHIVE_ARTIFACT }}

      # Finish
      - name: Delete previous nightly
        uses: ClementTsang/delete-tag-and-release@v0.3.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release new nightly
        uses: softprops/action-gh-release@v2
        with:
          name: nightly builds
          tag_name: latest
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: true
          files: |
            ${{ steps.store_linux_sdl2_x86_64.outputs.archive_path }}
            ${{ steps.store_linux_sdl1_x86_64.outputs.archive_path }}
            ${{ steps.store_windows_x86_64.outputs.archive_path }}
          token: ${{ secrets.GITHUB_TOKEN }}
